version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'
    networks:
      - appnet


  backend:
    build:
      context: .
      dockerfile: dockerfiles/backend.Dockerfile
    ports:
      - '8001:8001'
    depends_on:
      - mongo
    networks:
      - appnet

  frontend:
    build:
      context: .
      dockerfile: dockerfiles/frontend.Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - appnet

  reverseproxy:
    image: caddy
    ports:
      - '80:80'


networks:
  appnet:

volumes:
  mongodb_data: